#############################################
# GitLab CI for ifm3d-ros2
# Multi-arch build + publish + cosign + GHCR
# Fully dynamic: IFM3D_VERSION, ARCH, ROS2_DISTRO
#############################################

variables:
  KANIKO_VERSION: "1.25.6"  # Keep up-to-date with latest Kaniko release
  BASE_IMAGE: ros
  IFM3D_VERSION: "1.6.12"
  IMAGE_REGISTRY: ghcr.io/ifm
  IMAGE_NAME: ifm3d-ros2
  GHCR_TOKEN: $GHCR_TOKEN

stages:
  - build
  - publish

include:
  - local: .gitlab/build_matrix.yml
  - local: .gitlab/build_job.yml
  - local: .gitlab/rules.yml
  - local: .gitlab/publish_docker.yml