# Example configuration for an ODS application with two cameras.
# Expected to be used with ods.launch.py.

# By default, this file expects two 3D camera heads connected to
# port2 and port3, and one ODS application, "app0".

/ifm3d/ods:
  ros__parameters:
    config_file: "config/o3r_configs/o3r_ods.json"
    ip: 192.168.0.69
    pcic_port: 51010
    publish_best_effort: false # If true, most sensor messages will be published best_effort instead of reliable
    ods:
      frame_id: "ifm_base_link"
      publish_occupancy_grid: true
      publish_costmap: false
      publish_polar_occupancy_grid: true
      publish_extrinsic_calibration_correction: true
    use_timestamp_from_device: true # Use device time instead of ROS time for message stamping
