#!/usr/bin/env python3
# -*- python -*-

# 
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2019 ifm electronic, gmbh
# 

import argparse
import json
import sys

import rclpy
from ifm3d_ros2.srv import Dump

WAIT_SECS = 2.0
SRV_NAME = "/ifm3d/camera/Dump"
NODE_NAME = "ifm3d_ros2_dump_client"

def get_args():
    parser = argparse.ArgumentParser(
        description='Dump an ifm3d camera configuration to stdout as JSON',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('--srv', required=False, default=SRV_NAME,
                        help="The fully qualified `Dump' service to call")
    parser.add_argument('--node', required=False, default=NODE_NAME,
                        help="The node name of this service client")

    args = parser.parse_args(sys.argv[1:])
    return args

def main():
    args = get_args()

    rclpy.init()
    node = rclpy.create_node(args.node)
    cli = node.create_client(Dump, args.srv)
    req = Dump.Request()
    log = node.get_logger()

    try:
        while not cli.wait_for_service(timeout_sec=WAIT_SECS):
            log.info("Dump service not available, waiting...")

        fut = cli.call_async(req)
        rclpy.spin_until_future_complete(node, fut)

        res = fut.result()
        if res is not None:
            if res.status == 0:
                print(json.dumps(json.loads(res.config),
                      sort_keys=True, indent=4, separators=(',', ': ')))
            else:
                log.error("Dump failed with error: %s - %s" %
                          (str(res.status),
                           "Check the `ifm3d' logs for more detail"))
        else:
           log.warn("Service call failed %r" % (fut.exception(),))

    except KeyboardInterrupt:
        pass

    finally:
        node.destroy_node()
        rclpy.shutdown()

    return 0

if __name__ == '__main__':
    sys.exit(main())
