# Example configuration for two camera nodes
# Expected to be used with examples/combined_2d_3d.launch.py using default name and namespace
# Default setup: 2D camera head connected to port0 (pcic_port 50010) and 3D connected to port4 (pcic_port 50014)

/ifm3d/camera_2d:
  ros__parameters:
    config_file: ""
    buffer_id_list:
      - EXTRINSIC_CALIB
      - INTRINSIC_CALIB
      - INVERSE_INTRINSIC_CALIBRATION
      - JPEG_IMAGE
      - RGB_INFO
    ip: 192.168.0.69
    pcic_port: 50010  # port0 of the VPU (2D data)
    publish_best_effort: false # If true, most sensor messages will be published best_effort instead of reliable
    publish_uncompressed: true  # If true, launch will spawn a republish node to provide rgb_uncompressed image only for RGB
    tf:
      base_frame_name: "ifm_base_link"
      mounting_frame_name: "camera_mounting_link"
      optical_frame_name: "camera_2d_optical_link"
      publish_base_to_mounting: true
      publish_mounting_to_optical: true
    use_sim_time: false
    xmlrpc_port: 80

/ifm3d/camera_3d:
  ros__parameters:
    config_file: ""
    buffer_id_list:
      - CONFIDENCE_IMAGE
      - EXTRINSIC_CALIB
      - INTRINSIC_CALIB
      - INVERSE_INTRINSIC_CALIBRATION
      - NORM_AMPLITUDE_IMAGE
      - RADIAL_DISTANCE_IMAGE
      - RADIAL_DISTANCE_NOISE
      - REFLECTIVITY
      - TOF_INFO
      - XYZ
    ip: 192.168.0.69
    pcic_port: 50014  # port4 of the VPU (3D data)
    publish_best_effort: false # If true, most sensor messages will be published best_effort instead of reliable
    publish_uncompressed: true  # If true, launch will spawn a republish node to provide rgb_uncompressed image only for RGB
    tf:
      base_frame_name: "ifm_base_link"
      mounting_frame_name: "camera_mounting_link"
      optical_frame_name: "camera_3d_optical_link"
      publish_base_to_mounting: false  # already published by 2d node
      publish_mounting_to_optical: true
    use_sim_time: false
    xmlrpc_port: 80